SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O LEFT JOIN (SELECT ANIMAL_ID, DATETIME AS "IN_DATETIME"
                                    FROM ANIMAL_INS) I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE IN_DATETIME IS NULL