SELECT  DATE_FORMAT(SALES_DATE, '%Y') YEAR, 
        DATE_FORMAT(SALES_DATE, '%m') MONTH, 
        COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, 
        ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021%' ), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE '2021%' 
)
GROUP BY MONTH
ORDER BY YEAR ASC, MONTH ASC